(chore): add semantic-release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,37 +1,31 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
 
 executors:
   python-3-9-6:
     docker:
       - image: circleci/python:3.9.6
+  node-docker:
+    docker:
+      - image: circleci/node:17.6.0
 
-
-# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
-# See: https://circleci.com/docs/2.0/orb-intro/
 orbs:
-  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
-  # Orb commands and jobs help you with common scripting around a language/tool
-  # so you dont have to copy and paste it everywhere.
-  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
   python: circleci/python@1.5.0
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
-    # These next lines defines a Docker executors: https://circleci.com/docs/2.0/executor-types/
-    # You can specify an image from Dockerhub or use one of the convenience images from CircleCI's Developer Hub
-    # A list of available CircleCI Docker convenience images are available here: https://circleci.com/developer/images/image/cimg/python
-    # The executor is the environment in which the steps below will be executed - below will use a python 3.10.2 container
-    # Change the version below to your required version of python
+  generate-version:
+    executor: node-docker
+    steps:
+      - checkout
+      - run:
+        name: install semantic release dependencies in root
+        command: |
+          npm --prefix .semantic-release run installInRoot
+      - run:
+        name: run semantic release
+        command: npx semantic-release
+
+  build-and-test: 
     executor: python-3-9-6
-    # Checkout the code as the first step. This is a dedicated CircleCI step.
-    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
-    # Here we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
-    # Then run your tests!
-    # CircleCI will report the results back to your VCS provider.
     steps:
       - checkout
       - restore_cache:
@@ -51,13 +45,54 @@ jobs:
 
       - run:
           name: run unit tests
-          # This assumes pytest is installed via the install-package step above
           command: python -m pytest -v tests --cov=${CIRCLE_PROJECT_REPONAME/-/_}
 
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+  release:
+    executor: python-3-9-6
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+            - python-cache-{{ checksum "requirements.txt" }}
+      - run:
+        name: install dependencies
+        command: |
+          pip install -r requirements.txt
+          pip install twine
+      - run:
+        name: create the distribution
+        command: |
+          python setup.py sdist
+
+          CHECKS=$(twine check dist/* | grep -c "PASSED")
+          N_FILES=$(( $(ls -l dist | wc -l) -1 ))
+
+          if [[ $CHECKS -ne $N_FILES ]]
+          then
+            echo "twine checks failed"
+            exit 1
+          fi
+      - run:
+        name: push to pypi
+        command: |
+          twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
 workflows:
-  build-test: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
-    jobs:
-      - build-and-test
+  version: 2
+  build-release:
+    - generate-version
+        filters:
+          branches:
+            only: "main"
+    - build-and-test:
+        filters:
+          only: /.*/
+        branches:
+          ignore: "main"
+    - release:
+        requires:
+          - build-and-test
+        filters:
+          branches:
+            ignore: /.*/
+          tags:
+            only: /^deploy-.*/
